DROP TABLE BD.ARTICULOS;
CREATE TABLE BD.ARTICULOS (
   CODIGO_ARTICULO INT UNSIGNED NOT NULL AUTO_INCREMENT,
   DESCRIPCION_ARTICULO VARCHAR(40),
   PRECIO_UNIDAD_ARTICULO DECIMAL(11,2),
   CANTIDAD INT,
   CONSTRAINT ARTICULOS_COD_ART_PK PRIMARY KEY (CODIGO_ARTICULO)
);

DROP TABLE BD.LINEA_PEDIDO;
CREATE TABLE BD.LINEA_PEDIDO (
   CODIGO_LINEA_PEDIDO INT UNSIGNED NOT NULL AUTO_INCREMENT,
   CODIGO_ARTICULO INT,
   NUMERO_PEDIDO INT,
   PRECIO_UNIDAD_ARTICULO DECIMAL(11,2),
   NUMERO_UNIDADES_ARTICULO INT,
   PORCENTAJE_DESCUENTO DECIMAL(4,2),
   CONSTRAINT LINEA_PEDIDO_COD_LIN_PED_PK PRIMARY KEY (CODIGO_LINEA_PEDIDO)
);

DROP TABLE BD.PEDIDOS;
CREATE TABLE BD.PEDIDOS (
   NUMERO_PEDIDO INT UNSIGNED NOT NULL AUTO_INCREMENT,
   FECHA_PEDIDO DATE,
   PORTE_PEDIDO DECIMAL(11,2),
   SEGURO_PEDIDO DECIMAL(11,2),
   OTROS_CARGOS_PEDIDO DECIMAL(11,2),
   TOTAL_CARGOS_PEDIDO DECIMAL(11,2),
   TOTAL_BRUTO_PEDIDO DECIMAL(11,2),
   PORCENTAJE_IVA_PEDIDO INT,
   IVA_PEDIDO DECIMAL(11,2),
   TOTAL_FACTURA_PEDIDO DECIMAL(11,2),
   CODIGO_CLIENTE INT,
   CONSTRAINT PEDIDOS_NUM_PED_PK PRIMARY KEY (NUMERO_PEDIDO)
);